Integration 1.0.4.26 & make an order

diff --git a/git_home/wlan-common.git/sbin/wlan b/git_home/wlan-common.git/sbin/wlan
--- a/git_home/wlan-common.git/sbin/wlan
+++ b/git_home/wlan-common.git/sbin/wlan
@@ -125,6 +125,17 @@ wifi_updateconf() {
     echo "===!!!!=============time:`date +%s` wlan updateconf end======" >/dev/console
 }
 
+wifi_apscan() {
+	for device in ${2:-$DEVICES}; do
+		config_get iftype "$device" type
+		if eval "type wifiapscan_$iftype" 2>/dev/null >/dev/null; then
+			eval "wifiapscan_$iftype '$device'" || echo "$device($iftype): apscan failed"
+		else
+			echo "$device($iftype): Interface type not supported apscan"
+		fi
+	done
+}
+
 wifi_updown() {
 	#[ enable = "$1" ] && {
 	#	wifi_updown disable "$2"
@@ -490,6 +501,7 @@ Commands:
     toggle                           : toggle wireless radio (ON <-> OFF)
          --no-update-hw-btn-state    :: do not update "hw_btn_state"
     schedule <11g/11a> <on/off>      : do wireless schedule
+    apscan                           : do ap scan
     stainfo                          : show all attached wireless stations.
     radio <11g/11a> <arguments>      : actions related to radio
          --status                    :: show radio status (ON or OFF)
@@ -551,6 +563,7 @@ case "$1" in
 	wps) wifi_wps "$@";;
 	toggle) wifi_toggle "$@";;
 	schedule) wifi_schedule "$@";;
+	apscan) wifi_apscan "$@";;
 	stainfo) wifi_stainfo "$@";;
 	radio) wifi_radio "$@";;
 	up) wifi_updown "enable" "$2";;
