Version 1.0.4.3HF

diff --git a/git_home/wlan-common.git/sbin/wlan b/git_home/wlan-common.git/sbin/wlan
--- a/git_home/wlan-common.git/sbin/wlan
+++ b/git_home/wlan-common.git/sbin/wlan
@@ -345,6 +345,7 @@ wifi_toggle() {
 wifi_schedule() {
 	local band=$2
 	local newstate=$3
+	local guest=$4
 
 	if eval "type config_get_$CONFIGS" 2>/dev/null >/dev/null; then
 		eval "config_get_$CONFIGS _tmp_state hw_btn_state"
@@ -365,17 +366,17 @@ wifi_schedule() {
 	); done
 	if [ "$newstate" = "on" -a "$_tmp_state" = "on" ]; then
 		if eval "type config_set_$CONFIGS" 2>/dev/null >/dev/null; then
-			eval "config_set_$CONFIGS sched_status $band 0"
+			eval "config_set_$CONFIGS sched_status $band 0 $guest"
 		fi
 		if eval "type config_set_$CONFIGS" 2>/dev/null >/dev/null; then
-			eval "config_set_$CONFIGS wl_onoff $band 1"
+			eval "config_set_$CONFIGS wl_onoff $band 1 $guest"
 		fi
 	else
 		if eval "type config_set_$CONFIGS" 2>/dev/null >/dev/null; then
-			eval "config_set_$CONFIGS sched_status $band 1"
+			eval "config_set_$CONFIGS sched_status $band 1 $guest"
 		fi
 		if eval "type config_set_$CONFIGS" 2>/dev/null >/dev/null; then
-			eval "config_set_$CONFIGS wl_onoff $band 0"
+			eval "config_set_$CONFIGS wl_onoff $band 0 $guest"
 		fi
 	fi
 	if eval "type config_get_$CONFIGS" 2>/dev/null >/dev/null; then
@@ -387,7 +388,7 @@ wifi_schedule() {
 	if [ "$newstate" = "on" -a "$_tmp_state" = "on" ]; then
 		for driver in ${DRIVERS}; do (
 			if eval "type on_led_${driver}" 2>/dev/null >/dev/null; then
-				eval "on_led_${driver} $_tmp_radio_num $_tmp_security_type $_tmp_radio_type $_tmp_led_blinking_setting" || echo "$driver: on led failed"
+				eval "on_led_${driver} $_tmp_radio_num $_tmp_security_type $_tmp_radio_type $_tmp_led_blinking_setting $guest" || echo "$driver: on led failed"
 			else
 				echo "$driver: Interface type not supported"
 			fi
@@ -395,7 +396,7 @@ wifi_schedule() {
 	else
 		for driver in ${DRIVERS}; do (
 			if eval "type off_led_${driver}" 2>/dev/null >/dev/null; then
-				eval "off_led_${driver} $_tmp_radio_num $_tmp_security_type $_tmp_radio_type $_tmp_led_blinking_setting" || echo "$driver: off led failed"
+				eval "off_led_${driver} $_tmp_radio_num $_tmp_security_type $_tmp_radio_type $_tmp_led_blinking_setting $guest" || echo "$driver: off led failed"
 			else
 				echo "$driver: Interface type not supported"
 			fi
