Optimize WireGuard client init script

diff --git a/package/wireguard-tools/files/wg-client.init b/package/wireguard-tools/files/wg-client.init
--- a/package/wireguard-tools/files/wg-client.init
+++ b/package/wireguard-tools/files/wg-client.init
@@ -7,37 +7,47 @@ WIREGUARD_ON=$($CONFIG get wg-client)
 AP_MODE=$($CONFIG get ap_mode)
 BRIDGE_MODE=$($CONFIG get bridge_mode)
 EXTENDER_MODE=$($CONFIG get extender_mode)
-KVER=$( uname -a | awk -F "[ -]" '{ print $3 }')
+KVER=$(uname -a | awk -F "[ -]" '{ print $3 }')
+WGMTU="1420"
 WGConfig="/tmp/wg0.conf"
-LOG_FILE=/var/log/wireguard-client.log
+LOG_FILE="/var/log/wireguard-client.log"
+CONF_FILE="/etc/wireguard.conf"
 
 start() {
 	# Check if WireGuard client is enabled
 	if [ ! "$WIREGUARD_ON" == "1" ]; then
-		echo "WireGuard client is not enabled in nvram. Exit."
-		exit 1
-	fi
-	# Check WireGuard config file existence, exit if no such file
-	if [ ! -f /opt/configs/wireguard.conf ]; then
-		echo "File /opt/configs/wireguard.conf not found. Exit." | tee -a $LOG_FILE
+		echo "WireGuard client is not enabled in nvram. Exit." | tee -a $LOG_FILE
 		exit 0
 	fi
 
-	. /opt/configs/wireguard.conf
-	# WireGuard config (/opt/configs/wireguard.conf) should define the following:
-	# ---------------------------------------------------------------------------
-	# EndPoint="WireGuardProviderHostName"
-	# LocalIP="xxx.xxx.xxx.xxx"
-	# PrivateKey="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx="
-	# PublicKey="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx="
-	# Port="xxxx"
-	# ---------------------------------------------------------------------------
+	# Check WireGuard config file existence, exit if no such file
+	if [ ! -f $CONF_FILE ]; then
+		echo "Error: File $CONF_FILE not found." | tee -a $LOG_FILE
+		exit 1
+	fi
 
 	# Check if not router mode
 	if [ "$AP_MODE" == "1" ] || [ "$BRIDGE_MODE" == "1" ] || [ "$EXTENDER_MODE" == "1" ]; then
 		echo "Error: Not router mode." | tee -a $LOG_FILE
 		exit 1
 	fi
+
+	# Check if wg0 interface is available
+	ifconfig | grep -q wg0
+	if [ $? -eq 0 ]; then
+		echo "Error: wg0 interface already exists." | tee -a $LOG_FILE
+		exit 1
+	fi
+
+	# WireGuard config (/etc/wireguard.conf) should define the following:
+	# +-------------------------------------------------------------------------+
+	# | EndPoint="WireGuardProviderHostName"                                    |
+	# | LocalIP="xxx.xxx.xxx.xxx"                                               |
+	# | PrivateKey="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx="               |
+	# | PublicKey="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx="                |
+	# | Port="xxxx"                                                             |
+	# +-------------------------------------------------------------------------+
+	. $CONF_FILE
 
 	# Check if value of EndPoint is defined
 	if [ -z "$EndPoint" ]; then
@@ -75,16 +85,26 @@ start() {
 		echo "Error: Cannot get IP of $EndPoint." | tee -a $LOG_FILE
 		exit 1
 	fi
+	echo "Start WireGuard client. Please wait." | tee -a $LOG_FILE
 	echo "IP of EndPoint $EndPoint is $IP." | tee -a $LOG_FILE
+
+	sleep 25
 
 	# WireGuard: create wg0 interface
 	insmod /lib/modules/$KVER/wireguard.ko
 	ip link add dev wg0 type wireguard
 	ip address add dev wg0 $LocalIP/24
 	ip link set up dev wg0
-	ifconfig wg0 mtu 1420
+	ifconfig wg0 mtu $WGMTU
 
-	# WireGuard: create wg0 config
+	# Check if wg0 interface is available
+	ifconfig | grep -q wg0
+	if [ $? -ne 0 ]; then
+		echo "Error: Cannot create wg0." | tee -a $LOG_FILE
+		exit 1
+	fi
+
+	# WireGuard: create wg0 config (wg0.conf)
 	echo "[Interface]"		>  $WGConfig
 	echo "PrivateKey = $PrivateKey"	>> $WGConfig
 	echo "[Peer]"			>> $WGConfig
@@ -92,7 +112,7 @@ start() {
 	echo "Endpoint = $IP:$Port"	>> $WGConfig
 	echo "AllowedIPs = 0.0.0.0/0"	>> $WGConfig
 
-	# Set config file for wg0
+	# Set config file for wg0 interface
 	wg setconf wg0 $WGConfig >>$LOG_FILE 2>>$LOG_FILE
 
 	# Route all via wg0
@@ -101,7 +121,8 @@ start() {
 	ip route add 128/1 dev wg0
 	ip route delete default
 
-	# Restart firewall
-	net-wall rule
-	net-wall start
+	# Restart firewall to apply iptables rules for WireGuard
+	echo "Restart firewall to apply iptables rules for WireGuard client." | tee -a $LOG_FILE
+	net-wall rule | tee -a $LOG_FILE
+	net-wall start | tee -a $LOG_FILE
 }
